### ISSUE TITLE
can't import react "ReferenceError: could not load module filename 'react'"

### ISSUE THREAD

**Issue by Chingliu** [doodlewind/react-ssd1306#5]
I download react.js from https://unpkg.com/react@16/umd/react.production.min.js

as your code:
import './polyfill.js'
import React from 'react'

const App = props => {
  console.log(props.hello)
  return null
}
console.log(<App hello={'QuickJS'} />)

qjs to run it  said: "ReferenceError: could not load module filename 'react'"
so I changed import React from 'react'  to import React from './react.js', this time 
I got "SyntaxError: export 'default' in module './react.js' is ambiguous"

Could your help me to point where I made mistake.

**Comment by doodlewind** [comment]
Hi, this ES6 codebase needs be bundled by Rollup first. Please run `npm install` in `/app` first, then `npm run dev` to generate dist bundle. Moreover, `npm run dev-web` will open up a Web emulator (global `parcel-bundler` is required in this case).

**Comment by Chingliu** [comment]
Thanks, it fixed my problem
